
networks:
  bluesky-net:
    driver: bridge

services:
  pds:
    container_name: pds
    image: bluesky_pds
    ports:
      - "2583:2583"
    networks:
      - bluesky-net
    restart: unless-stopped
    volumes:
      - /data/vm/pds/pds:/pds 
    env_file:
      -  pds.env

  postgres:
    image: postgres:15
    container_name: pds-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/vm/pds-postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - bluesky-net

