version: '3.9'

networks:
  bluesky-net:
    driver: bridge

services:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:0.4
    ports:
      - "2583:2583"
    network_mode: bluesky-net
    restart: unless-stopped
    volumes:
      - type: bind
        source: /vm/data/pds/pds
        target: /pds
    env_file:
      - /pds/pds.env

